version: '3.8'

services:
  web:
    build: .
    image: fma-classifier:latest
    container_name: fma-classifier
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/model
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - MODEL_PATH=/app/models/gtzan_lstm_model.keras
      - GUNICORN_WORKERS=2
      - GUNICORN_THREADS=4
      - MAX_CONTENT_LENGTH=16777216  # 16MB max upload size
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  nginx:
    image: nginx:alpine
    container_name: fma-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./static:/var/www/html/static
    depends_on:
      - web

networks:
  default:
    name: gtzan-network
